# Generated by Django 4.2.1 on 2023-05-07 09:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeinmap",
            name="group_place",
        ),
        migrations.RemoveField(
            model_name="placeinmap",
            name="what_todo",
        ),
        migrations.AddField(
            model_name="placeinmap",
            name="group_place",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="group_place",
                to="api.groupplace",
            ),
        ),
        migrations.AddField(
            model_name="placeinmap",
            name="what_todo",
            field=models.ManyToManyField(
                blank=True, related_name="what_todo", to="api.whattodo"
            ),
        ),
    ]
