# Generated by Django 4.2.1 on 2023-06-13 21:03

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0004_alter_arialinmap_id_alter_channelgeomap_id_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TypePermissionToken",
            fields=[
                (
                    "id",
                    models.AutoField(
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи",
                    ),
                ),
                (
                    "description",
                    models.CharField(max_length=255, verbose_name="Описание типа"),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="TokenPermission",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="Идентификатор записи UUIDv4",
                    ),
                ),
                ("token", models.CharField(max_length=255, verbose_name="Токен")),
                (
                    "count_use",
                    models.SmallIntegerField(
                        max_length=256, verbose_name="Количество использований токена"
                    ),
                ),
                (
                    "type_permission",
                    models.ManyToManyField(
                        related_name="type_permissions", to="api.typepermissiontoken"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
