# Версия Docker Compose
version: '3.3'

# Описание сервисов
services:
  # Описание сервиса "app"
  app:
    # Настройки сборки образа
    build:
      context: .
      dockerfile: Dockerfile_Django
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_DJANGO}:8181"
    # Примонтирование локальной директории к контейнеру
    # volumes:
      # - ./backend:/app
    # Переменные окружения
    environment:
      POSTGRES_HOST: db # Хост для подключения к БД
      POSTGRES_USER: ${POSTGRES_USER} # Пользователь для подключения к БД (переменная из файла .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль для подключения к БД (переменная из файла .env)
      POSTGRES_DB: ${POSTGRES_DB} # Имя БД (переменная из файла .env)
      POSTGRES_PORT: ${POSTGRES_PORT} # Порт для подключения к БД (переменная из файла .env)
      IP_ADR: ${IP_ADR}
      HOST_PORT_NGINX_STATIC: ${HOST_PORT_NGINX_STATIC}
      HOST_PORT_VUE_SERVER: ${HOST_PORT_VUE_SERVER}
      HOST_PORT_NGINX_VUE: ${HOST_PORT_NGINX_VUE}
      DEBUG: ${DEBUG}
    depends_on:
      - db

  # Описание сервиса "db"
  db:
    # Использование готового образа
    image: postgres:12-alpine
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Переменные окружения
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Пользователь для подключения к БД (переменная из файла .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль для подключения к БД (переменная из файла .env)
      POSTGRES_DB: ${POSTGRES_DB} # Имя БД (переменная из файла .env)
    # Примонтирование локальной директории к контейнеру
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_POSTGRESQL}:5432"

  # Описание сервиса "nginx"
  # Используется для раздачи html
  nginx_vue:
    # Использование готового оброза
    image: nginx:alpine
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_NGINX_VUE}:80"
    # Примонтирование локальной директории к контейнеру
    volumes:
      - ./front_vue/dist:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # Описание сервиса "nginx_static"
  # Используется для раздачи изображений
  nginx_static:
    # Использование готового оброза
    image: nginx:alpine
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_NGINX_STATIC}:80"
    # Примонтирование локальной директории к контейнеру
    volumes:
      # Основной проброс статических файлов - изображений
      - ./front_vue/static:/usr/share/nginx/html
      # Проброс для статических файлов Django
      - ./backend/static:/usr/share/nginx/html/static_django
      - ./nginx.conf:/etc/nginx/conf.d/default.conf

  # Описание сервиса "vue"
  # Dev сервер для Vue.js, запускается только в DEV режиме. На проде не запускается
  vue_dev_server:
    build:
      context: .
      dockerfile: ./conf_build/Dockerfile_Vue_Dev
    restart: always
    volumes:
      - ./front_vue:/app
      - /app/node_modules
    ports:
      - "${HOST_PORT_VUE_SERVER}:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true

networks:
  default: