version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "8181:8181"
    volumes:
      - .:/app
    environment:
      - PYTHONUNBUFFERED=1
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432

  db:
    image: postgres:12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: app
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    ports:
      - "8182:5432"
