---
- hosts: all # Применить к каждому хосту
  become: yes # Получить права суперпользователя
  tasks: # Список задач для выполнения
    - name: Update APT cache # Обновить кеш APT
      apt: update_cache=yes cache_valid_time=3600

    - name: Install Python, pip, and PostgreSQL # Установка Python, pip и PostgreSQL
      apt:
        pkg:
          - python3-pip
          - python3-venv
          - libpq-dev
          - postgresql

    - name: Install Poetry globally # Установка Poetry глобально
      pip:
        name: poetry

    - name: Create a virtual environment using Poetry # Создание виртуального окружения с использованием Poetry
      command: poetry env use python3.11
      args:
        chdir: /app

    - name: Install dependencies from pyproject.toml # Установка зависимостей из файла pyproject.toml
      command: poetry install --no-root
      args:
        chdir: /app

    - name: Start PostgreSQL service # Запуск службы PostgreSQL
      systemd:
        name: postgresql
        state: started
        enabled: yes

    - name: Configure PostgreSQL to listen on all addresses # Настройка PostgreSQL для прослушивания всех адресов
      lineinfile:
        path: /etc/postgresql/12/main/postgresql.conf
        regexp: "^#listen_addresses"
        line: "listen_addresses = '*'"

    - name: Configure PostgreSQL to allow connections from all IPs # Настройка PostgreSQL для разрешения подключений со всех IP-адресов
      lineinfile:
        path: /etc/postgresql/12/main/pg_hba.conf
        line: "host all all all md5"

    - name: Restart PostgreSQL service # Перезапуск службы PostgreSQL
      systemd:
        name: postgresql
        state: restarted
