# Generated by Django 4.2.1 on 2023-05-03 20:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0002_rename_place_in_map_placeinmap_group_place"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="placeinmap",
            name="group_place",
        ),
        migrations.AddField(
            model_name="placeinmap",
            name="group_place",
            field=models.ManyToManyField(
                blank=True, null=True, related_name="group_place", to="api.groupplace"
            ),
        ),
    ]
