# Generated by Django 4.2.1 on 2023-05-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api", "0003_remove_placeinmap_group_place_placeinmap_group_place"),
    ]

    operations = [
        migrations.AlterField(
            model_name="placeinmap",
            name="group_place",
            field=models.ManyToManyField(
                blank=True, related_name="group_place", to="api.groupplace"
            ),
        ),
    ]
