---
- name: Развертывание проекта {{ name_app }}
  hosts: all
  become: true
  vars:
      name_app: chillmap_backend
      git_url: "https://github.com/denisxab/{{ name_app }}"
      path_app: "/app/{{ name_app }}"
  tasks:
      - name: Получения проекта на удаленном сервер через GIT
        import_tasks: send_files_app.yml

      - name: Копировать файл с сервера на локальную машину
        block:
            - name: Копировать файл с сервера на локальную машину
              synchronize:
                  src: "../../.gitignore"
                  dest: "{{ path_app }}/.gitignore"
                  delete: yes

            - name: Сформировать строку исключения для rsync из .gitignore
              shell: |
                  while IFS= read -r line; do
                    echo "--exclude=$line"
                  done < {{ path_app }}/.gitignore
              register: rsync_excludes
              changed_when: false

            - name: Копирование проекта на удаленный сервер
              synchronize:
                  src: "../../../"
                  dest: "{{ path_app }}"
                  delete: yes
                  recursive: yes
                  rsync_opts: "{{ rsync_excludes.stdout_lines }}"

      - name: Замена строки в файле .env
        block:
            - name: Замена строки в файле .env с IP_ADR
              lineinfile:
                  path: "{{ path_app }}/.env"
                  regexp: "^IP_ADR="
                  line: "IP_ADR={{ ansible_host }}"

            - name: Замена строки в файле .env с DEBUG
              lineinfile:
                  path: "{{ path_app }}/.env"
                  regexp: "^DEBUG="
                  line: "DEBUG=False"

      - name: Установка invoke и docker-compose если это необходимо
        import_tasks: install_invoke_and_docker_compose.yml

      # Пока не рализован HTTPS, проблема в том что все приложения должны так же работать по HTTPS, в том числе Django
      # - name: Создать SSL сертифкаты на сервере если их нет
      #   when: is_ssl == 'true'
      #   block:
      #       - name: Узнать наличие файла certificate.crt
      #         stat:
      #             path: "{{path_app}}/devops/ssl/certificate.crt"

      #         register: stat_certificate

      #       - name: Узнать наличие файла private_key
      #         stat:
      #             path: "{{path_app}}/devops/ssl/private_key"
      #         register: stat_private_key

      #       - name: Создать SSL сертифкаты если их нет
      #         command:
      #             cmd: invoke ssl.create
      #             chdir: "{{ path_app }}"
      #         when: not stat_certificate.stat.exists and not stat_private_key.stat.exists

      - name: Перезапуск проекта
        command:
            cmd: invoke dck.restart --prod --detach --echo
            chdir: "{{ path_app }}"
