# Версия Docker Compose
version: '3.8'

# Описание сервисов
services:
  # Описание сервиса "app"
  app:
    # Настройки сборки образа
    build:
      context: .
      dockerfile: Dockerfile_Django
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_DJANGO}:8181"
    # Примонтирование локальной директории к контейнеру
    volumes:
      - ./backend:/app
    # Переменные окружения
    environment:
      POSTGRES_HOST: db # Хост для подключения к БД
      POSTGRES_USER: ${POSTGRES_USER} # Пользователь для подключения к БД (переменная из файла .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль для подключения к БД (переменная из файла .env)
      POSTGRES_DB: ${POSTGRES_DB} # Имя БД (переменная из файла .env)
      POSTGRES_PORT: ${POSTGRES_PORT} # Порт для подключения к БД (переменная из файла .env)
    depends_on:
      - db

  # Описание сервиса "db"
  db:
    # Использование готового образа
    image: postgres:12-alpine
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Переменные окружения
    environment:
      POSTGRES_USER: ${POSTGRES_USER} # Пользователь для подключения к БД (переменная из файла .env)
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль для подключения к БД (переменная из файла .env)
      POSTGRES_DB: ${POSTGRES_DB} # Имя БД (переменная из файла .env)
    # Примонтирование локальной директории к контейнеру
    volumes:
      - ./pgdata:/var/lib/postgresql/data
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_POSTGRESQL}:5432"

  # Описание сервиса "vue-dev"
  vue-dev:
    build:
      context: .
      dockerfile: Dockerfile_Vue
    restart: always
    volumes:
      - ./front_vue:/app
      - /app/node_modules
    ports:
      - "${HOST_PORT_VUE_SERVER}:8080"
    environment:
      - CHOKIDAR_USEPOLLING=true

  # Описание сервиса "nginx"
  nginx:
    # Использование готового оброза
    image: nginx:alpine
    # Автоматически перезапускать контейнер при его остановке
    restart: always
    # Пробрасывание порта
    ports:
      - "${HOST_PORT_NGINX}:80"
    # Примонтирование локальной директории к контейнеру
    volumes:
      - ./front_vue/static:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
networks:
  default: