---
- name: Развертывание проекта
  hosts: all
  become: true
  vars:
    path_app: "/app/chillmap_backend2"
  tasks:
    - name: Сборка Vue.js приложения на локальной машине перед диплоем
      delegate_to: localhost
      command: "docker build -t dockerfile_vue_prod -f ./conf_build/Dockerfile_Vue_Build ."
      args:
        chdir: "../"

    - name: Запуск Docker контейнера на локальном сервере
      delegate_to: localhost
      command: "docker run -v ./front_vue:/app -v /app/node_modules dockerfile_vue_prod"
      args:
        chdir: "../"

    - name: Изменение владельца директории на локальном сервере
      delegate_to: localhost
      command: "sudo chown $USER:$USER -R ./front_vue"
      args:
        chdir: "../"

    - name: Копировать файл с сервера на локальную машину
      synchronize:
        src: "../.gitignore"
        dest: "{{ path_app }}/.gitignore"
        delete: yes

    - name: Сформировать строку исключения для rsync из .gitignore
      shell: |
        while IFS= read -r line; do
          echo "--exclude=$line"
        done < {{ path_app }}/.gitignore
      register: rsync_excludes
      changed_when: false

    - name: Копирование проекта на удаленный сервер
      synchronize:
        src: "../../"
        dest: "{{ path_app }}"
        delete: yes
        recursive: yes
        rsync_opts: "{{ rsync_excludes.stdout_lines }}"

    - name: Замена строки в файле .env с IP_ADR
      lineinfile:
        path: "{{ path_app }}/.env"
        regexp: "^IP_ADR="
        line: "IP_ADR={{ ansible_host }}"

    - name: Замена строки в файле .env с DEBUG
      lineinfile:
        path: "{{ path_app }}/.env"
        regexp: "^DEBUG="
        line: "DEBUG=False"

    - name: Проверка наличия библиотеки invoke
      command:
        cmd: pip show invoke
      register: pip_check
      ignore_errors: true

    - name: Установка invoke и docker-compose
      include_tasks: install_invoke_and_docker_compose.yml
      when: pip_check.rc != 0

    - name: Перезапуск проекта
      command:
        cmd: invoke dck.restart --prod --detach --echo
        chdir: "{{ path_app }}"
