---
- name: Развертывание проекта
  hosts: all
  become: true
  vars:
    path_app: "/app/chillmap_backend"
  tasks:
    - name: Обновление apt
      apt:
        update_cache: yes

    - name: Добавление Docker GPG ключа
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Добавление Docker репозитория
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu focal stable"
        state: present

    - name: Создание папки {{ path_app }}
      file:
        path: "{{ path_app }}"
        state: directory
        mode: "0755"

    - name: Установка зависимостей
      apt:
        name: "{{ item }}"
        state: present
        install_recommends: yes
      loop:
        - apt-transport-https
        - ca-certificates
        - curl
        - software-properties-common
        - nano
        - docker-ce
        - docker-compose
        - python3-pip

    - name: Установка дополнительных пакетов через pip
      pip:
        name: "{{ item }}"
        state: present
      loop:
        - invoke
        - python-dotenv

    - name: Клонирование проекта
      git:
        repo: https://github.com/denisxab/chillmap_backend
        dest: "{{ path_app }}"
        force: yes

    - name: Замена строки в файле .env с IP_ADR
      lineinfile:
        path: "{{ path_app }}/.env"
        regexp: "^IP_ADR="
        line: "IP_ADR={{ ansible_host }}"

    - name: Замена строки в файле .env с DEBUG
      lineinfile:
        path: "{{ path_app }}/.env"
        regexp: "^DEBUG="
        line: "DEBUG=False"

    - name: Перезапуск проекта
      command:
        cmd: invoke dck.restart --prod --detach --echo
        chdir: "{{ path_app }}"
