# Используйте официальный образ Python
FROM python:3.11

# Установка рабочей директории
WORKDIR /app_django

COPY ./backend/pyproject.toml ./backend/poetry.lock ./

RUN apt update && apt install -y make postgresql-client htop

# Установка Poetry
RUN pip install --no-cache-dir poetry

# Установка зависимостей с использованием Poetry
RUN poetry config virtualenvs.create false \
    && poetry install --no-interaction

# Копирование остальных файлов приложения в рабочую директорию
COPY ./backend/ ./

# Установка переменной среды, чтобы вывод не буферизовался
ENV PYTHONUNBUFFERED=1

# Запуск команды по умолчанию
CMD python manage.py migrate && \ 
    make css_to_drf && \
    make loaddata && \ 
    python manage.py collectstatic --noinput && \
    daphne conf.asgi:application -b 0.0.0.0 -p 8181
